name: CI

on: [ push, pull_request ]

jobs:
  # unit-tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: "17"
  #         distribution: "adopt"

  #     - name: Run unit tests
  #       run: mvn clean test -Dtest="unittest.controller.*Test,unittest.service.*Test"

  # end-to-end-tests:
  #   needs: unit-tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: "17"
  #         distribution: "adopt"

  #     - name: Install dependencies
  #       run: sudo apt-get install -y libxss1 libappindicator1 libindicator7

  #     - name: Setup ChromeDriver
  #       uses: nanasess/setup-chromedriver@master

  #     - name: Build with Maven
  #       run: mvn clean package -DskipTests

  #     - name: Run application
  #       run: nohup java -jar target/moviecards-0.0.1-SNAPSHOT.jar &

  #     - name: Run e2e tests
  #       run: mvn test -Dtest="*E2ETest"
  #       env:
  #         CHROME_DRIVER_PATH: /usr/local/bin/chromedriver
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Run tests
        run: mvn clean verify
